rover_bot:
  # Publish all joint states ------------this will allow the system to publish current state of the joint-----------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30  
  

  # Effort Controllers --------------------this is for the continuous joint state-------------------
  leftWheel_effort_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  rightWheel_effort_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}

